### ISSUE TITLE
Arabic Language output is reversed

### ISSUE THREAD

**Issue by lisaied** [tesseract-ocr/tessdata#12] opened 2016-02-10 21:26 UTC
Hello,

I'm new with tesseract-ocr x3, I'm using the command line to ocr arabic tif. but all words positions are reversed (opposite).

Any help you can provide to reverse ara lang in tesseract x3.
I'm using cygwin to run tesstrain.sh but till now ocr output is reversed.

Many Thanks in Advance.

**Comment by amitdo** [comment] 2016-05-12 08:58
This is duplicate of https://github.com/tesseract-ocr/tesseract/issues/212

**Comment by amitdo** [comment] 2017-08-17 15:09
@zdenop, please close this issue.

**Closed** 2017-08-17 18:05 UTC
