### ISSUE TITLE
The release is corrupted

### ISSUE THREAD

**Issue by V-kto** [tesseract-ocr/tessdata#161] opened 2022-06-15 13:17 UTC
# Description

I have downloaded the following release : https://github.com/tesseract-ocr/tessdata/releases/tag/4.1.0

I have an error when I try to unzip it. 

# Tested Environments

- Mac OSX 12.4
- Amazon Linux 2 (Docker container)

# Reproduce

Run the following commands

```shell
wget https://github.com/tesseract-ocr/tessdata/archive/refs/tags/4.1.0.zip
unzip ./4.1.0.zip
```

You will get this

```
Archive:  ./4.1.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./4.1.0.zip or
        ./4.1.0.zip.zip, and cannot find ./4.1.0.zip.ZIP, period.
```

**Comment by stweil** [comment] 2022-06-15 16:38
I can confirm that problem. The release zip files are provided by GitHub, so there is nothing we can do to fix it.

**Comment by zdenop** [comment] 2022-06-15 16:57
tessdata repository is huge repository and:

> ZIP format had a 4 GB limit on various things (uncompressed size of a file, compressed size of a file, and total size of the archive), as well as a limit of 65,535 entries in a ZIP archive.

so it seems you chose to use the wrong technology. Use `git clone --depth 1 https://github.com/tesseract-ocr/tessdata.git` for downloading all data.

**Comment by stweil** [comment] 2022-06-15 17:02
The tar.gz file is about 565 MiB. The zip file 543 MiB, far away from the limit but the size seems to be too small.

`git clone` is a good alternative which has several advantages compared to downloading a zip or tar.gz file.

**Comment by stweil** [comment] 2022-06-15 21:20
> Is the root problem understood?

Ask Microsoft, the owners of GitHub. The zip files are created automatically by GitHub.

> Also, we had similar issues with the tar.gz file.

In my test tar.gz worked fine.

**Comment by stweil** [comment] 2022-06-15 21:35
I now tried several downloads of the zip file using wget. The resulting files had different sizes although there was no download error.

**Comment by stweil** [comment] 2022-06-15 21:44
More tests confirmed that the download terminates after exactly 100 seconds, resulting in a partial file.

**Comment by stweil** [comment] 2022-06-15 21:50
I close this issue as we cannot solve it, but there is a good alternative way to get the data using `git clone` (see above).

**Closed by stweil** 2022-06-15 21:50 UTC

**Comment by V-kto** [comment] 2022-06-17 15:47
Hi ! 

Thank you for your reply. I will use `git clone` instead. About `tar.gz` in my remember it did not work either but i'm not sure.

Anyway, the main thing is that I can use tessdata somehow !

thank you for your explanations and yout time :)
